### ISSUE TITLE
When an application is run in subdirectory mode, the page is not displayed correctly.

### ISSUE THREAD

**Issue by m-bird** [kaishuu0123/blockdiag-api#12]
What happens? 
-----------------
With subdirectory mode enabled and running behind a reverse proxy, the page does not display properly.

Note
-------
The api server works fine in subdirectories.
However, the path to static content is not prefixed with a subdirectory.

**Comment by kaishuu0123** [comment]
@m-bird 

Thank you for your contribution.
Fixed by #13.
